services:
  postgresdb:
    image: postgres:alpine
    restart: always
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - agrocontrol
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s

  mongodb:
    networks:
      - agrocontrol
    container_name: mongodb
    image: mongo
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - agrocontrol
    depends_on:
      postgresdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  
networks:
  agrocontrol:
    driver: bridge

